# Generated by Django 3.2 on 2021-04-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deprt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('img', models.ImageField(upload_to='department')),
            ],
            options={
                'verbose_name': 'Deprt',
                'verbose_name_plural': 'Deprts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dept', models.TextField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('img', models.ImageField(upload_to='doctor')),
                ('ph_no', models.TextField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('available', models.BooleanField(default=True)),
                ('deprt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.deprt')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ('name',),
            },
        ),
    ]
